---
# 通用（杂项）设置
common:
  loggingLevel: debug # 日志等级，可选 ["debug", "info", "warning", "error"]
  gpt.numPerRequestTranslate: 9 # 单次翻译句子数量，不建议太大
  gpt.numPerRequestProofRead: 7 # 单次校润句子数量，不建议修改
  retryFail: true # (True/False)每次启动时重翻所有翻译失败的句子（目前仅NewBing会翻译失败）
  multiThread: false # (True/False)多线程（暂不可用）
  gpt.degradeBackend: false # 是否将 GPT4 的key用于 GPT3.5 的请求
  gpt.lineBreaksImprovementMode: false # (True/False)换行符改善模式，减少丢换行符情况，但可能导致循环重试
  gpt.restoreContextMode: true # (True/False)重启自动恢复上下文
  gpt.enableProofRead: false # (True/False)是否开启译后校润，仅NewBing，GPT4支持
# 代理设置
proxy:
  # 是否启用代理
  enableProxy: false
  proxies:
    - address: socks5://127.0.0.1:10818
      # username: foo
      # password: bar
# 字典
dictionary:
  default_dictionary_folder: Dict #通用字典文件夹
  # 预处理字典
  preDict:
    - 00通用字典_译前.txt
    - 01H字典_矫正_译前.txt # 用于口齿不清的矫正
    - (project_dir)项目字典_译前.txt # (project_dir)代表字典在项目文件夹
  # GPT 字典
  gpt.dict:
    - GPT字典.txt
    - (project_dir)项目GPT字典.txt
  # 后处理字典
  postDict:
    - 00通用字典_符号_译后.txt # 符号矫正
    - 00通用字典_译后.txt
    - (project_dir)项目字典_译后.txt
# 与翻译后端所特定的设置
backendSpecific:
  GPT35: # GPT3.5 官方 API
    tokens: # 令牌列表
      - token: sk-xxxxxxxx # 你的令牌
        endpoint: https://api.openai.com # OPENAI API请求的域名，使用转发或第三方API时修改
      - token: sk-yyyyyyyy
        endpoint: ""
    defaultEndpoint: https://api.openai.com # 默认 API 端点，一般不修改
  GPT4: # GPT4 官方 API
    tokens:
      - token: sk-xxxxxxxx
        endpoint: ""
      - token: sk-yyyyyyyy
        endpoint: ""
    defaultEndpoint: https://api.openai.com
  ChatGPT: # ChatGPT / GPT3.5(4) 非官方 API，模拟网页操作
    access_tokens:
      - access_token: xxx
    accounts:
      - username: foo
        password: bar
      - username: bar
        password: foo
  bingGPT4:
    cookiePath:
      - newbing_cookies/cookie1.json # 你的 cookies 文件
      - newbing_cookies/cookie2.json # 你的 cookies 文件
# 问题分析机制配置
problemAnalyze:
  GPT35: # GPT35 / ChatGPT
    - 词频过高
    - 本无括号
    - 本无引号
    - 残留日文
    - 丢失换行
    - 多加换行
    - 比日文长
  GPT4: # GPT4 / ChatGPT
    - 词频过高
    - 本无括号
    - 本无引号
    - 残留日文
    - 丢失换行
    - 多加换行
  bingGPT4:
    - 词频过高
    - 本无括号
    - 本无引号
    - 残留日文
    - 丢失换行
    - 多加换行
